import { Inter } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";

import Navbar from "./components/Navbar";

// Initializing the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata object for the webpage
export const metadata = {
  title: "Video streaming",
  description: "Generated by create next app",
};

// RootLayout component that wraps around other components
export default async function RootLayout({ children }) {

  // Retrieving current user information asynchronously
  const currentUser = await getCurrentUser();

  // Returning the JSX structure
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Rendering the Navbar component and passing currentUser as a prop */}
        <Navbar currentUser={currentUser} />
        {/* Rendering the children components */}
        {children}
      </body>
    </html>
  );
}