import { Inter } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";

import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Video streaming",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
